server:
  port: 8881
  servlet:
    context-path: /repeat
  tomcat:
    uri-encoding: UTF-8

spring:
  redis:
    database: 15
    host: 192.16.30.26
    port: 6379
    #password: admin
    #连接超时时间(毫秒)
    timeout: 2000
    lettuce:
      pool:
        # 连接池最大连接数(使用负值表示没有限制)
        maxActive: 8
        # 连接池最大阻塞等待时间(使用负值表示没有限制)
        maxWait: 5000
        # 连接池中的最大空闲连接
        maxIdle: 8
        # 连接池中的最小空闲连接
        minIdle: 0
  thymeleaf:
    prefix: classpath:/templates/
  resources:
    static-locations: classpath:/static/
